railway_final/booking/urls.py
from django.conf.urls import url

from booking import views


app_name = 'booking'

urlpatterns = [
    url(r'^index/$', views.index, name='index'),
    url(r'^aboutus/$', views.aboutus, name='aboutus'),
    url(r'^stationinfo/$', views.stationinfo, name='stationinfo'),
    
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login'),
    url(r'^logout_user/$', views.logout_user, name='logout'),
    url(r'^search/', views.search_results, name='search'),
    url(r'^booking/', views.book_ticket, name='book_ticket'),
    url(r'^ticket/(?P<pk>[0-9]+)/$', views.GetTicket.as_view(), name='get_ticket'),
    url(r'^ticketdetails/(?P<ticket_id>[0-9]+)/$', views.ticketdetails, name='ticketdetails'),
]

railway_final/railway/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
	url(r'',include('booking.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

railway_final/booking/models.py
from django.db import models


class Train(models.Model):
    ''' Train Information '''
    number = models.IntegerField(unique=True)
    name = models.CharField(max_length=300)
    date = models.DateField()
    departure = models.TimeField(blank=True, null=True)
    arrival = models.TimeField(blank=True, null=True)
    route = models.ForeignKey('Route')
    third_ac = models.PositiveIntegerField(default=10)
    second_ac = models.PositiveIntegerField(default=10)
    sleeper = models.PositiveIntegerField(default=10)
    fare = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    def decrease_third_ac(self):
        self.third_ac -= 1
        self.save()

    def decrease_second_ac(self):
        self.second_ac -= 1
        self.save()

    def decrease_sleeper(self):
        self.second_ac -= 1
        self.save()


class Station(models.Model):
    ''' Station '''
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Route(models.Model):
    ''' Route '''
    name = models.CharField(max_length=20)
    source = models.ForeignKey('Station', related_name='source')
    destination = models.ForeignKey('Station', related_name='destination')
    route_path = models.ManyToManyField("Station", through="RoutePath")

    def __str__(self):
        return self.name


class RoutePath(models.Model):
    route = models.ForeignKey('Route')
    station = models.ForeignKey('Station')
    order = models.IntegerField()

    def __str__(self):
        return "%s-%s-%d" % (self.route.name, self.station.name, self.order)


class Ticket(models.Model):
    ''' Ticket '''
    GENDER_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    train = models.ForeignKey('Train')


    def __str__(self):
        return self.first_name + self.last_name

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

railway_final/booking/forms.py
from django import forms
from django.contrib.auth.models import User
from booking.models import Ticket

class TicketForm(forms.ModelForm):

    class Meta:
        model = Ticket
        fields = ('first_name', 'last_name', 'gender')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

railway_final/booking/views.py
from django.shortcuts import get_list_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views.generic.detail import DetailView
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from .forms import UserForm
from booking.models import Train, Ticket
from booking.forms import TicketForm
from booking.utils import class_name, update_count
from .models import *

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/index/')

    context = {
        "form": form,
    }
    return render(request,'register.html', context)

def logout_user(request):

    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request,'login.html',context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'index.html',{})
            else:
                return render(request, 'login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'login.html', {'error_message': 'Invalid login'})
    return render(request, 'login.html')



def index(request):
    if request.user.is_authenticated():
        return render(request,'index.html')
    else:
        form = UserForm(request.POST or None)
        context = {
        "form": form,
        }
        return render(request,'login.html',context)

def search_results(request):
    ''' Display search results filter by queries '''
    trains = get_list_or_404(Train.objects.filter(
        date=request.GET.get('date'),
        route__source__name=request.GET.get('source'),
        route__destination__name=request.GET.get('destination'),
    ))
    context = {'trains': trains}
    return render(request, 'search.html', context)


def book_ticket(request):
    ''' Book Tikcet'''
    if request.method == 'GET':
        form = TicketForm()
        train = Train.objects.get(pk=request.GET.get('train'))
        seat_class = request.GET.get('class')
        train_context = {
            'train': train,
            'class_model_name': seat_class,
            'class': class_name(seat_class),
            'seat': getattr(train, seat_class)
        }
    elif request.method == 'POST':
        form = TicketForm(request.POST)
        if form.is_valid():
            train = Train.objects.get(pk=request.POST.get('train'))
            form.instance.train = train
            instance = form.save()
            # update count
            update_count(train, request.POST.get('class'))
            return HttpResponseRedirect(reverse('booking:get_ticket', args=(instance.id,)))
    else:
        return HttpResponseRedirect('/')

    return render(request, 'booking.html', {'form': form, 'train_context': train_context})


def ticketdetails(request,ticket_id):
    a=Ticket.objects.get(id=ticket_id)
    traindet=a.train
    b=Train.objects.get(name=traindet)
    routename=b.route
    c=Route.objects.get(name=routename)
    source=c.source
    dest=c.destination
    trainsdet=Ticket.objects.get(id=ticket_id)
    f = Train.objects.get(number = b.number)
    fare = f.fare
    context={
    'source':source,
    'dest':dest,
    'trainsdet':trainsdet,
    'fare':fare,
    }
    return render(request,'completeticket.html',context) 


def aboutus(request):
    return render(request,'aboutus.html',{})

def stationinfo(request):
    return render(request,'stationinfo.html',{})


class GetTicket(DetailView):
    model = Ticket
    template_name = 'ticket.html'
    context_object_name = 'ticket'

railway_final/booking/templates/aboutus.html
{% extends "base.html" %} 

{% block content %}
  <h1>About us page</h1>
  <p>Metro Rail Corporation Limited (MRCL),is a Special Purpose Vehicle entrusted with the responsibility of implementation of Metro Rail Project;</p>
  <p>it not only adds to the beauty of City skyline, but immensely adds to the comfort level of travel. Besides this, Metro is a major environment friendly addition to the City as it significantly contribute to the reduction of carbon emissions.</p><p>The project has an East-West corridor - 18.10 km long, starting from Baiyappanahalli in the East and terminating at Mysore Road terminal in the West and a 24.20 km North-South corridor commencing at Nagasandra in the North and terminating at Puttenahalli in the South</p>
  <p>The commercial operations on <strong>Reach-1 (MG Road to Baiyappanahalli station)</strong> have opened on <strong>20th October 2011</strong>. The commercial operations on <strong>Reach-3 (Nagasandra to Mantri Square Sampige Road Station)</strong> have commenced on <strong>1st March 2014</strong>. The commercial operations on <strong>Reach-3B (Peenya Industry to Nagasandra)</strong> have commenced on <strong>1st May 2015</strong> and the commercial operations on <strong>Reach-2 (Magadi Road to Mysore Road Terminal)</strong> have commenced on <strong>18th November 2015</strong>.</p><p>This is the First Metro rail project in India commissioned with 750V DC Third Rail on Standard Guage.</p>
{% endblock %}

railway_final/booking/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
  <!-- Required meta tags always come first -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/css/bootstrap.min.css" integrity="sha384-y3tfxAZXuh4HwSYylfB+J125MxIs6mR5FOHamPBG064zB+AFeWH94NdvaCBm8qnd" crossorigin="anonymous">
  

<style >
  #introduction {
  background: linear-gradient(rgba(100,181,246 ,1), rgba(0,0,0,0.8)), url('https://www.travelchinaguide.com/images/photogallery/2015/high-speed.jpg') 0% 0%/cover 


}

body{
  background-image: url('{% static 'img/bullet-train.jpg'%}');
}

</style>


   <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.2/js/bootstrap.min.js" integrity="sha384-vZ2WRJMwsjRMW/8U7i6PWi6AlO1L79snBrmgiDpgIWJ82z8eA5lenwvxbMV1PAh7" crossorigin="anonymous"></script>
  </head>

<body>


<!-- <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/index">Railway Ticketing System</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="/index">Home</a></li>
      <li><a href="{% url 'booking:aboutus' %}">About us</a></li>
      <li><a href="{% url 'booking:stationinfo' %}"></a>Station info</li>
      <li><a href="{% url 'booking:logout' %}">Logout</a></li>
    </ul>
  </div>
</nav>
    <br> --> 

 <!-- <nav class="navbar navbar-inverse bg-inverse">

  <div class="nav navbar-nav nav-inline">
      <li class=""><a class="" href="#">Home</a></li>
      <li class=""><a class="" href="#">Aboutus</a></li>
      
      <li class=""><a class="" href="#">Station-info</a></li>

      <li class=""><a class="" href="#">My Tickets</a></li>
      <li class=""><a class="" href="#">Logout</a></li>


  </div>
</nav> -->
 <!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse bg-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/index">Railway Ticketing</a>
    </div>
    <ul class="nav navbar-nav">
      <li><a href="{% url 'booking:aboutus' %}">About us</a></li>
      <li><a href="{% url 'booking:stationinfo' %}">Station-info</a></li>
      <li><a href="{% url 'booking:logout' %}">Logout</a></li>
    </ul>
  </div>
</nav>
  
<!-- <div class="container">
  <h3>Basic Navbar Example</h3>
  <p>A navigation bar is a navigation header that is placed at the top of the page.</p>
</div> -->


  {% block content %} {% endblock %}
</body>

</html>

railway_final/booking/templates/booking.html
{% extends "base.html" %} 

{% block content %}
  
  <div class="container">
    <div class="row text-xs-center">
      <h2>Book a Ticket</h2>
      <h3>Train Name: {{ train_context.train.name }}</h3>
      <p>Class: {{ train_context.class }}</p>
      <p>Available Seat: {{ train_context.seat }}</p>
      {% if train_context.seat == 0 %} 
      <p>All seats are booked</p>
      {% else %}
      <form action="{% url 'booking:book_ticket' %}" class="form-inline" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="text" id="id_train" name="train" value="{{ train_context.train.pk }}" hidden>
        <input type="text" name="class" value="{{ train_context.class_model_name }}" hidden>
        <button type="submit" class="btn btn-primary">Get Ticket</button>
      </form>
      {% endif %}
    </div>
  </div>
{% endblock %}

railway_final/booking/templates/completeticket.html
{% extends "base.html" %} 

{% block content %}

<h1>booking confirmed</h1>
  <div class="container">
    <h1 style="color: blue">Ticket details</h1>
    <h4>Source:{{source}}</h4>
    <h4>Destination:{{dest}}</h4>
    <h4>fare:{{fare}}</h4>
<h1 style="color:blue">Passenger details</h1>


    <h4>Firstname:{{trainsdet.first_name}}</h4>
    <h4>Lastname:{{trainsdet.last_name}}</h4>
    <h4>Gender:{{trainsdet.gender}}</h4>
    <h4>Train:{{trainsdet.train}}</h4>

  </div>

{% endblock %}

railway_final/booking/templates/form_template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" for="song_title">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

railway_final/booking/templates/index.html
{% extends "base.html" %} 

{% block content %}


<!-- <h1 style="color:blue">Railway Ticketing System</h1>
 -->

</br>
</br>
</br>
</br>
</br>
</br>
</br>
</br>

<section id="main">
  <div class="container">
    <div class="row">
      <div class="col-md-12 ">
      <form action="{% url 'booking:search' %}" class="form-inline ">
        <!-- <fieldset class="form-group">
          <input type="text" name="source" class="form-control" placeholder="Enter source" required>
        </fieldset>

        <fieldset class="form-group">
          <input type="text" name="destination" class="form-control" placeholder="Enter destination" required>
        </fieldset> -->
        
        <select name="source"  style="width:259px;height: 30px;">
  <option value="0">Select Source</option>
  <option value="MAJESTIC">Majestic</option>
  <option value="YESHWANTHPURA">Yeshwanthpura</option>
  <option value="INDRANAGAR">IndraNagar</option>
  <option value="JPNAGAR">JPNagar</option>
  <option value="MGRoad">MGRoad</option>
 </select>
       <select name="destination"  style="width:259px; height: 30px;">
  <option value="0">Select Destination</option>
  <option value="MAJESTIC">Majestic</option>
  <option value="YESHWANTHPURA">Yeshwanthpura</option>
  <option value="INDRANAGAR">IndraNagar</option>
  <option value="JPNAGAR">JPNagar</option>
  <option value="MGROAD">MGRoad</option>
 </select>
 <fieldset class="form-group">
          <input type="date" name="date" class="form-control" min="2017-1-06" required>
        </fieldset>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div>
  </div>

</div>




</section>

{% endblock %}

railway_final/booking/templates/login.html
{% extends "visitor.html" %} 
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block content %}
<div class="jumbotron" style="background-color:#dbd3e8">
<div class="container-fluid fill-viewport">

<div class ="container" style="margin-left: 350px;">
    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    </br>
                    </br>
                    </br>


                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'booking:login'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'booking:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
    </div>
</div>
</div>

{% endblock %}

railway_final/booking/templates/register.html
{% extends "visitor.html" %} 

{% block content %}
<section id = "Register">
<div class="jumbotron" style="background-color:#dbd3e8">
<div class="container-fluid fill-viewport">

<div class ="container" style="margin-left: 350px;">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                </div>
            </div>
        </div>
    </div>
</div>
</div>
</div>
</section>
{% endblock %}

railway_final/booking/templates/search.html
{% extends "base.html" %} 

{% block content %}
  

  </br>
</br>
</br>

</br>
</br>

</br>
<!-- 
 
      <form action="{% url 'booking:search' %}" class="form-inline">
        <fieldset class="form-group">
          <input type="text" name="source" class="form-control" required>
        </fieldset>
        <fieldset class="form-group">
          <input type="text" name="destination" class="form-control" required>
        </fieldset>
        <fieldset class="form-group">
          <input type="date" name="date" class="form-control" required>
        </fieldset>
        <button type="submit" class="btn btn-primary">Search</button>
      </form>
    </div> -->
     <div class="container">
    <div class="row">
    <div class="col-md-8">
      {% if trains %}
        <ul>
          {% for train in trains %}
            
            <li>
              {{ train.name }}
              <form action="{% url 'booking:book_ticket' %}" class="form-inline">
                <select name="class">
                  <option value="second_ac">default</option>
                  <!-- <option value="third_ac">3A</option>
                  <option value="sleeper">Sleeper</option>
                </select> -->
                <input type="text" id="id_train" name="train" value="{{ train.pk }}" hidden>
                <button type="submit" class="btn btn-primary">Book</button>
              </form>
            </li>

          {% endfor %}
        </ul>
        {% else %}
        <h1>no trains found</h1>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

railway_final/booking/templates/stationinfo.html
{% extends "base.html" %} 

{% block content %}
<style type="text/css">
	h2 {color: black;}
	p {color: #253d63;}
	li {color :#2a3ccc;}
</style>
<h1>Stationinfo</h1>
 <h2>RVCT</h2>
                <p>
                    A Remaining Value Checking Terminal (RVCT) is installed near Customer Care to enable passengers check balance and previous transactions on their tokens and smart card
                </p>

 <h2>Ticket Vending Machine</h2>
                <p>
                    Automatic Ticket Vending machines are installed at MG Road,Indiranagar & Baiyappanahalli stations to enable passengers buy tokens and load value on their smart cards by cash. 

                </p>

<h2>Customer Care</h2>
                <p>
                    The Customer care is located on the station to assist passengers regarding any problem about their tickets. It is usually located between entry and exit gates and is accessible from both paid and unpaid area.Those who need to pay excess fares or obtain assistance with malfunctioning tickets may also visit the Customer Care at stations.
                </p>


<h2>Passenger Information Display Boards</h2>
                <p>
                    Passenger Information Display Boards are installed near the Automatic gates and on platform to provide real-time information to passengers about the arrival of trains.
                </p>


<h2>In case of fire at the stations:</h2>
            <ul><li>There are manual call points for giving a fire alarm signal if fire is discovered.</li><li>Follow instructions given by Namma Metro staff to evacuate the station.</li><li>Use the nearest escalator or staircase to reach the street level.</li><li>Leave the station through nearest exit immediately.</li><li>Take care when walking to the exit.</li><li>Do not use lifts in case of fire.Incident report on the train:</li></ul>

<h2>Incident report on the train:</h2>
            <div><ul><li>Press PEA button inside the train to connect to train operator.</li><li>Follow instructions given by train operator.</li></ul></div>
        </div>


{% endblock %}

railway_final/booking/templates/ticket.html
{% extends "base.html" %} 

{% block content %}

<h1>booking confirmed</h1>
  <div class="container">
    <div class="row text-xs-center">
    	
    	
    <p>Name:   {{ ticket.get_full_name }}</p>
    <p>Gender: {{ ticket.gender }}</p>
    <p>Train: {{ ticket.train.name }}</p>
    <p>Ticket id:{{ ticket.id}}</p>
    </br>
    </br>
    </br>
        <a href="{% url 'booking:ticketdetails' ticket.id %}">View full ticket</a>
    </div>
  </div>

{% endblock %}

railway_final/booking/templates/visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
   <style type="text/css">
     .fill-viewport {
  min-height: 100vh
}
   </style>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #27292d">

 <button> <a class="navbar-brand" href="{% url 'booking:index' %}">Railway Ticketing</a></button>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <button> <a class="navbar-brand" href="{% url 'booking:register' %}">Register</a></button>
      </li>
  
        <button> <a class="nav-link navbar-brand" href="{% url 'booking:login' %}">&nbsp; Login</a></button>
      </li>

    </ul>
  </div>

  
</nav>
{% block content %}
{% endblock %}
</body>
</html>